# Initial Data Profiling

## Project Overview

This notebook performs an initial exploration and profiling of the raw Superstore dataset before any data cleaning or transformation.

The objective is to understand:

- The structure and size of the dataset
- Column names and data types
- Missing values
- Duplicate records
- Unique values and identifiers
- Numerical distributions
- Date ranges and consistency
- Potential data quality issues
- The likely transactional grain of the dataset

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries imported successfully.")

Libraries imported successfully.

## 2. Locate the Raw Dataset

verify that Jupyter is looking in the correct location

In [3]:
# Current notebook folder
nt_folder = Path.cwd()

# Project root = parent folder of "Initial Data Profiling"
project_root = nt_folder.parent

# Raw data folder
raw_data_folder = project_root / "Raw_Data"

# Dataset file
data_file = raw_data_folder / "sample_superstore(csv).csv"

print("Notebook folder:")
print(nt_folder)

print("\nProject root:")
print(project_root)

print("\nRaw data folder:")
print(raw_data_folder)

print("\nDataset:")
print(data_file)

Notebook folder:
C:\Users\may\Documents\Syntecxhub_Sales_Performance_Dashboard\Initial Data Profiling

Project root:
C:\Users\may\Documents\Syntecxhub_Sales_Performance_Dashboard

Raw data folder:
C:\Users\may\Documents\Syntecxhub_Sales_Performance_Dashboard\Raw_Data

Dataset:
C:\Users\may\Documents\Syntecxhub_Sales_Performance_Dashboard\Raw_Data\sample_superstore(csv).csv

In [4]:
if not data_file.exists():
    raise FileNotFoundError(
        f"\nDataset not found at:\n{data_file}\n\n"
        "Check:\n"
        "1. The CSV is inside the Raw_Data folder\n"
        "2. The file is named exactly sample_superstore(csv).csv"
    )

print("Dataset found successfully.")

Dataset found successfully.

## 3. Load the Raw Dataset

In [5]:
df = pd.read_csv(data_file)

print("Dataset loaded successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

Dataset loaded successfully.
Rows: 10,194
Columns: 21

In [6]:
# overview of the dataset
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

## 4. Dataset Structure

In [7]:
print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]:,}")

print("\nColumn names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Number of rows: 10,194
Number of columns: 21

Column names:
1. Row ID
2. Order ID
3. Order Date
4. Ship Date
5. Ship Mode
6. Customer ID
7. Customer Name
8. Segment
9. Country/Region
10. City
11. State/Province
12. Postal Code
13. Region
14. Product ID
15. Category
16. Sub-Category
17. Product Name
18. Sales
19. Quantity
20. Discount
21. Profit

In [8]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [9]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

`Row ID`
  - **Meaning:** Unique identifier for a transaction/order line
  - **usage:** Likely fact-table row key
    
`Order ID`
  - **Meaning:** Identifier of the customer order
  - **usage:** Groups multiple transaction lines into one order
    
`Order Date`
  - **Meaning:** Date on which the order was placed
  - **usage:** Time analysis

`Ship Date`
  - **Meaning:** Date on which the order was shipped
  - **usage:** Shipping/time analysis

`Ship Mode`
  - **Meaning:** Shipping method used
  - **usage:** Shipping analysis

`Customer ID`
  - **Meaning:** Unique identifier for a customer
  - **usage:** Customer dimension key

`Customer Name`
  - **Meaning:** Customer's name
  - **usage:** Customer identification/display

`Segment`
  - **Meaning:** Customer segment, e.g. Consumer, Corporate, Home Office
  - **usage:** Customer segmentation

`Country/Region`
  - **Meaning:** Country associated with the transaction
  - **usage:** Geographic analysis

`City`
  - **Meaning:** Customer/order city
  - **usage:** Geographic analysis

`State/Province`
  - **Meaning:** State or province
  - **usage:** Geographic analysis

`Postal Code`
  - **Meaning:** Postal/ZIP code
  - **usage:** Geographic analysis

`Region`
  - **Meaning:** Broader geographical region such as East/West/Central
  - **usage:** Regional analysis

`Product ID`
  - **Meaning:** Unique identifier for a product
  - **usage:** Product dimension key

`Category`
  - **Meaning:** High-level product category
  - **usage:** Product/category analysis

`Sub-Category`
  - **Meaning:** More specific product grouping
  - **usage:** Product analysis

`Product Name`
  - **Meaning:** Product description/name
  - **usage:** Product-level analysis

`Sales`
  - **Meaning:** Revenue generated by the transaction line
  - **usage:** Main KPI

`Quantity`
  - **Meaning:** Number of units sold
  - **usage:** Volume analysis

`Discount`
  - **Meaning:** Discount applied to the transaction
  - **usage:** Pricing/discount analysis

`Profit`
  - **Meaning:** Profit generated by the transaction line
  - **usage:** Profitability analysis

the final records include the date `12/30/2026`. Since the current date is `9/28/2026`, those are future-dated relative to today. This may simply be the particular version of the sample dataset downloaded. Therefor, for the analysis, we should first establish the complete date range and document it.

***Note: this is an observation based on the current date and status of the projects creation. In the future, it may become irrelevant.***

## 5. Data Types

In [10]:
data_types = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values
})

data_types

            Column Data Type
0           Row ID     int64
1         Order ID    object
2       Order Date    object
3        Ship Date    object
4        Ship Mode    object
5      Customer ID    object
6    Customer Name    object
7          Segment    object
8   Country/Region    object
9             City    object
10  State/Province    object
11     Postal Code    object
12          Region    object
13      Product ID    object
14        Category    object
15    Sub-Category    object
16    Product Name    object
17           Sales   float64
18        Quantity     int64
19        Discount   float64
20          Profit   float64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

**Note**: 

- change `Order Date` and `Ship Date` from ***OBJECT*** to ***DATE/DATETIME***
- Change `Postal Code` to ***VARCHAR/NVARCHAR***

## 6. Missing Values

In [12]:
missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isna().sum().values,
    "Missing %": (df.isna().mean() * 100).round(2).values
})

missing_summary = missing_summary.sort_values(
    by="Missing Values",
    ascending=False
)

missing_summary

            Column  Missing Values  Missing %
0           Row ID               0        0.0
11     Postal Code               0        0.0
19        Discount               0        0.0
18        Quantity               0        0.0
17           Sales               0        0.0
16    Product Name               0        0.0
15    Sub-Category               0        0.0
14        Category               0        0.0
13      Product ID               0        0.0
12          Region               0        0.0
10  State/Province               0        0.0
1         Order ID               0        0.0
9             City               0        0.0
8   Country/Region               0        0.0
7          Segment               0        0.0
6    Customer Name               0        0.0
5      Customer ID               0        0.0
4        Ship Mode               0        0.0
3        Ship Date               0        0.0
2       Order Date               0        0.0
20          Profit               0        0.0

In [13]:
# Show only columns that actually contain missing values
missing_only = missing_summary[
    missing_summary["Missing Values"] > 0
]

missing_only

Empty DataFrame
Columns: [Column, Missing Values, Missing %]
Index: []

There are currently no NULL/missing values in the raw dataset. Therefore,  No missing-value treatment is currently required based on this profiling stage.

--> perform SQL validation later, so the database enforces/checks this as part of the pipeline.

## 7. Duplicate Records

In [14]:
duplicate_count = df.duplicated().sum()

print(f"Number of exact duplicate rows: {duplicate_count:,}")

Number of exact duplicate rows: 0

In [15]:
# See the duplicate rows if any exist
duplicates = df[df.duplicated(keep=False)]

duplicates.head(20)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State/Province, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

**Note**: No duplicate-row removal is required based on the current profiling results.

## 8. Unique Values

Inspect the number of distinct values in every column.

This helps identify:

- Identifier columns
- Categorical columns
- Potentially duplicated entities
- High-cardinality fields

In [16]:
unique_summary = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [df[column].nunique(dropna=True) for column in df.columns]
})

unique_summary = unique_summary.sort_values(
    by="Unique Values",
    ascending=True
)

unique_summary

            Column  Unique Values
8   Country/Region              2
14        Category              3
7          Segment              3
12          Region              4
4        Ship Mode              4
19        Discount             12
18        Quantity             14
15    Sub-Category             17
10  State/Province             59
9             City            542
11     Postal Code            654
6    Customer Name            800
5      Customer ID            804
2       Order Date           1242
3        Ship Date           1338
16    Product Name           1849
13      Product ID           1862
1         Order ID           5111
17           Sales           5837
20          Profit           7334
0           Row ID          10194

1. `Row ID`: is exactly equal to the number of rows in the dataset, meaning it can be used for the individual transaction line in the future fact table.

2. `Order ID`: has 5111 unique values, meaning Orders contain multiple transaction lines. This strongly supports: ***Fact grain = one row per order/product transaction line***

3. `Customer ID` and `Customer Name`: the first has 804 unique values while the second has 800 unique values. This could mean that some names are shared by more than one customer ID; therefore, we need to check whether *one Customer ID corresponds to exactly one Customer Name* and whether *one Customer Name corresponds to multiple Customer IDs*.

4. `Product ID` and `Product Name`: the first has 1862 unique values while the second has 1849 unique values. It may be that: *one product name → multiple product IDs*

5. `Category`, `Segment`, `Region` and `Ship Mode`: are the low-cardinality categorical fields that will work as dimensions/attributes in Power BI.

6. `Sub-Category`: This gives us a useful product hierarchy:

***Category --> Sub-Category -- Product***. 

This will be useful for drill-down analysis in Power BI.

7. `Geography`: There is 2 countries + 59 states/provinces + 542 cities + 654 postal codes + 4 regions.  Meaning the dataset supports geographic analysis at several levels:

***Country --> State/Province --> City --> Postal Code***

While `Region` provides a separate higher-level regional grouping.

## 9. Important Identifier Analysis

The Superstore dataset contains several fields that may act as business identifiers:

- Order ID
- Customer ID
- Product ID
- Row ID

We need to understand their cardinality before designing the SQL model.

In [18]:
possible_identifiers = [
    "Row ID",
    "Order ID",
    "Customer ID",
    "Product ID"
]

identifier_results = []

for column in possible_identifiers:
    if column in df.columns:
        identifier_results.append({
            "Column": column,
            "Total Rows": len(df),
            "Unique Values": df[column].nunique(),
            "Duplicate Values": df[column].duplicated().sum()
        })

identifier_summary = pd.DataFrame(identifier_results)

identifier_summary

        Column  Total Rows  Unique Values  Duplicate Values
0       Row ID       10194          10194                 0
1     Order ID       10194           5111              5083
2  Customer ID       10194            804              9390
3   Product ID       10194           1862              8332

## 10. Transactional Grain Analysis

The dataset contains multiple rows for some orders.

This section determines the number of transaction lines associated with each Order ID and helps identify the appropriate grain for the future fact table.

In [19]:
# Number of transaction lines per order

order_line_counts = (
    df.groupby("Order ID")
      .size()
      .sort_values(ascending=False)
)

print(f"Total transaction rows: {len(df):,}")
print(f"Unique orders: {df['Order ID'].nunique():,}")
print(f"Average transaction lines per order: {order_line_counts.mean():.2f}")
print(f"Minimum transaction lines for an order: {order_line_counts.min():,}")
print(f"Maximum transaction lines for an order: {order_line_counts.max():,}")

Total transaction rows: 10,194
Unique orders: 5,111
Average transaction lines per order: 1.99
Minimum transaction lines for an order: 1
Maximum transaction lines for an order: 14

***The number of Unique orders (5,111) indicates that the grain cannot be one row per order.***

***Creating a fact table by assuming each row was a complete order would incorrectly treat one order containing five products as five separate orders, which would subsequently produce an incorrect KPI.***

In [20]:
# Distribution of transaction lines per order

transaction_line_distribution = (
    order_line_counts
    .value_counts()
    .sort_index()
    .rename_axis("Transaction Lines per Order")
    .reset_index(name="Number of Orders")
)

transaction_line_distribution

    Transaction Lines per Order  Number of Orders
0                             1              2593
1                             2              1242
2                             3               612
3                             4               344
4                             5               164
5                             6                72
6                             7                51
7                             8                16
8                             9                10
9                            10                 3
10                           11                 2
11                           12                 1
12                           14                 1

In [21]:
# Orders containing more than one transaction line

multi_line_orders = order_line_counts[order_line_counts > 1]

print(f"Orders with multiple transaction lines: {len(multi_line_orders):,}")
print(
    f"Percentage of orders with multiple lines: "
    f"{len(multi_line_orders) / len(order_line_counts) * 100:.2f}%"
)

Orders with multiple transaction lines: 2,518
Percentage of orders with multiple lines: 49.27%

In [22]:
# Orders with the largest number of transaction lines

largest_orders = (
    order_line_counts
    .head(10)
    .reset_index(name="Transaction Lines")
)

largest_orders

         Order ID  Transaction Lines
0  US-2026-100111                 14
1  US-2026-157987                 12
2  US-2025-165330                 11
3  US-2025-108504                 11
4  US-2024-126977                 10
5  US-2024-131338                 10
6  US-2025-105732                 10
7  US-2025-145177                  9
8  US-2024-104346                  9
9  US-2024-158421                  9

The dataset contains 10,194 transaction rows and 5,111 unique orders.

Because the number of transaction rows is greater than the number of orders, and approximately 49.27% of orders contain multiple transaction lines, the dataset operates at a transaction/order-line grain rather than an order grain.

Each source row represents an individual transaction line associated with an Order ID. An order can therefore contain one or more transaction lines, with the largest observed order containing 14 lines.

Row ID contains 10,194 unique values and is therefore a strong candidate for uniquely identifying each transaction line.

This indicates that the transaction-line grain must be preserved during SQL transformation. The dataset shouldn't be aggregated to one row per Order ID before building the fact table because this would remove product-level, quantity, discount, sales, and profit information.

## 11. Identifier Relationship Analysis

Determine whether important identifiers consistently map to the same descriptive attributes.

The following relationships will be investigated:

- Customer ID → Customer Name
- Customer ID → Segment
- Product ID → Product Name
- Product ID → Category
- Product ID → Sub-Category
- Order ID → Customer ID
- Order ID → Order Date
- Order ID → Ship Date

These checks identify possible inconsistencies before SQL modeling.

### 11. 1. Customer Relationship Analysis

In [23]:
# Customer ID consistency

customer_id_consistency = (
    df.groupby("Customer ID")
      .agg(
          Customer_Names=("Customer Name", "nunique"),
          Segments=("Segment", "nunique")
      )
      .sort_values(
          ["Customer_Names", "Segments"],
          ascending=False
      )
)

customer_id_consistency.head(20)

             Customer_Names  Segments
Customer ID
AA-10315                  1         1
AA-10375                  1         1
AA-10480                  1         1
AA-10645                  1         1
AB-10015                  1         1
AB-10060                  1         1
AB-10105                  1         1
AB-10150                  1         1
AB-10165                  1         1
AB-10255                  1         1
AB-10600                  1         1
AC-10420                  1         1
AC-10450                  1         1
AC-10615                  1         1
AC-10660                  1         1
AD-10180                  1         1
AF-10870                  1         1
AF-10885                  1         1
AG-10270                  1         1
AG-10300                  1         1

Each Customer ID consistently corresponds to:

one customer name
one segment

Conclusion: The customer information is consistent. We can safely use Customer ID as the customer identifier when creating the customer dimension.

In [24]:
# Customer IDs with multiple names or segments

inconsistent_customers = customer_id_consistency[
    (customer_id_consistency["Customer_Names"] > 1) |
    (customer_id_consistency["Segments"] > 1)
]

print(
    f"Customer IDs with inconsistent name/segment mappings: "
    f"{len(inconsistent_customers):,}"
)

inconsistent_customers

Customer IDs with inconsistent name/segment mappings: 0

Empty DataFrame
Columns: [Customer_Names, Segments]
Index: []

In [27]:
# Customer names associated with multiple Customer IDs

customer_name_consistency = (
    df.groupby("Customer Name")["Customer ID"]
      .nunique()
      .sort_values(ascending=False)
)

multiple_ids_same_name = customer_name_consistency[
    customer_name_consistency > 1
]

print(
    f"Customer names associated with multiple Customer IDs: "
    f"{len(multiple_ids_same_name):,}"
)

multiple_ids_same_name.head(20)

Customer names associated with multiple Customer IDs: 1

Customer Name
Harry Olson    5
Name: Customer ID, dtype: int64

The name Harry Olson appears with 5 different Customer IDs.

This does not necessarily mean the data is wrong. It could represent different customers who happen to have the same name, or that he has multiple acoounts.

Conclusion: We should not merge customers based on their names. Customer ID is the reliable identifier, not Customer Name.

***Overall conclusion***

Customer ID → 1 Name + 1 Segment
Customer Name → can correspond to multiple Customer IDs

Therefore, for our SQL model: **Use Customer ID as the primary business identifier for customers.**

### 11. 2. Product Relationship Analysis

In [29]:
# Product ID consistency

product_id_consistency = (
    df.groupby("Product ID")
      .agg(
          Product_Names=("Product Name", "nunique"),
          Categories=("Category", "nunique"),
          Sub_Categories=("Sub-Category", "nunique")
      )
      .sort_values(
          ["Product_Names", "Categories", "Sub_Categories"],
          ascending=False
      )
)

product_id_consistency.head(20)

                 Product_Names  Categories  Sub_Categories
Product ID
FUR-BO-10002213              2           1               1
FUR-CH-10001146              2           1               1
FUR-FU-10001473              2           1               1
FUR-FU-10004017              2           1               1
FUR-FU-10004091              2           1               1
FUR-FU-10004270              2           1               1
FUR-FU-10004848              2           1               1
FUR-FU-10004864              2           1               1
OFF-AP-10000576              2           1               1
OFF-AR-10001149              2           1               1
OFF-BI-10002026              2           1               1
OFF-BI-10004632              2           1               1
OFF-BI-10004654              2           1               1
OFF-PA-10000357              2           1               1
OFF-PA-10000477              2           1               1
OFF-PA-10000659              2           1               1
OFF-PA-10001166              2           1               1
OFF-PA-10001970              2           1               1
OFF-PA-10002195              2           1               1
OFF-PA-10002377              2           1               1

In [30]:
# Product IDs with inconsistent descriptive attributes

inconsistent_products = product_id_consistency[
    (product_id_consistency["Product_Names"] > 1) |
    (product_id_consistency["Categories"] > 1) |
    (product_id_consistency["Sub_Categories"] > 1)
]

print(
    f"Product IDs with inconsistent product information: "
    f"{len(inconsistent_products):,}"
)

inconsistent_products

Product IDs with inconsistent product information: 32

                 Product_Names  Categories  Sub_Categories
Product ID
FUR-BO-10002213              2           1               1
FUR-CH-10001146              2           1               1
FUR-FU-10001473              2           1               1
FUR-FU-10004017              2           1               1
FUR-FU-10004091              2           1               1
FUR-FU-10004270              2           1               1
FUR-FU-10004848              2           1               1
FUR-FU-10004864              2           1               1
OFF-AP-10000576              2           1               1
OFF-AR-10001149              2           1               1
OFF-BI-10002026              2           1               1
OFF-BI-10004632              2           1               1
OFF-BI-10004654              2           1               1
OFF-PA-10000357              2           1               1
OFF-PA-10000477              2           1               1
OFF-PA-10000659              2           1               1
OFF-PA-10001166              2           1               1
OFF-PA-10001970              2           1               1
OFF-PA-10002195              2           1               1
OFF-PA-10002377              2           1               1
OFF-PA-10003022              2           1               1
OFF-ST-10001228              2           1               1
OFF-ST-10004950              2           1               1
TEC-AC-10002049              2           1               1
TEC-AC-10002550              2           1               1
TEC-AC-10003832              2           1               1
TEC-MA-10001148              2           1               1
TEC-PH-10001530              2           1               1
TEC-PH-10001795              2           1               1
TEC-PH-10002200              2           1               1
TEC-PH-10002310              2           1               1
TEC-PH-10004531              2           1               1

***The results show 32 Product IDs linked to 2 different Product Names. This indicates that the same Product ID has been recorded with different names, while its category and sub-category stay the same.***

In [31]:
# Product names associated with multiple Product IDs

product_name_consistency = (
    df.groupby("Product Name")["Product ID"]
      .nunique()
      .sort_values(ascending=False)
)

multiple_ids_same_product = product_name_consistency[
    product_name_consistency > 1
]

print(
    f"Product names associated with multiple Product IDs: "
    f"{len(multiple_ids_same_product):,}"
)

multiple_ids_same_product.head(20)

Product names associated with multiple Product IDs: 17

Product Name
Staples                                          10
Staple envelope                                   9
Easy-staple paper                                 8
Staples in misc. colors                           7
Staple remover                                    3
Staple holder                                     3
KI Adjustable-Height Table                        2
DAX Wood Document Frame                           2
Peel & Seel Recycled Catalog Envelopes, Brown     2
Eldon Wave Desk Accessories                       2
Okidata C610n Printer                             2
Prang Drawing Pencil Set                          2
Avery Non-Stick Binders                           2
Staple magnet                                     2
#10- 4 1/8" x 9 1/2" Recycled Envelopes           2
Staple-based wall hangings                        2
Storex Dura Pro Binders                           2
Name: Product ID, dtype: int64

The results here show that there are 17 product names associated with multiple Product IDs.

Meaning, the relationship is not simply: Product ID ↔ Product Name

--> There are some inconsistencies in the product identifiers/names.

This indicates that we need to investigate the 32 inconsistent Product IDs and determine which product name should be retained when creating dim_product later on.

Because `Category` and `Sub-Category` are consistent for those 32 IDs, the problem appears to be specifically with the Product Name, not the product classification.

**Conclusion:**

Product ID is not perfectly consistent with Product Name in the raw dataset. Therefore, product relationships must be validated and standardized during the SQL cleaning stage before creating the product dimension. The rows should not be removed.

### 11. 3. Order Consistency

In [32]:
# Check whether each order consistently maps to one customer

order_customer_consistency = (
    df.groupby("Order ID")["Customer ID"]
      .nunique()
)

multiple_customers_per_order = order_customer_consistency[
    order_customer_consistency > 1
]

print(
    "Orders associated with multiple customers:",
    len(multiple_customers_per_order)
)

Orders associated with multiple customers: 2

In [33]:
# Check whether each order has one order date

order_date_consistency = (
    df.groupby("Order ID")["Order Date"]
      .nunique()
)

multiple_order_dates = order_date_consistency[
    order_date_consistency > 1
]

print(
    "Orders associated with multiple Order Dates:",
    len(multiple_order_dates)
)

Orders associated with multiple Order Dates: 0

In [34]:
# Check whether each order has one ship date

order_ship_date_consistency = (
    df.groupby("Order ID")["Ship Date"]
      .nunique()
)

multiple_ship_dates = order_ship_date_consistency[
    order_ship_date_consistency > 1
]

print(
    "Orders associated with multiple Ship Dates:",
    len(multiple_ship_dates)
)

Orders associated with multiple Ship Dates: 0

***The order data is mostly consistent. The 2 orders linked to multiple customers need investigation, but no changes should be made yet. The Order Date and Ship Date relationships are consistent.***

## 12. Numerical Variables

The main numerical measures are:

- Sales
- Quantity
- Discount
- Profit

These variables will later be used for KPIs and DAX calculations.

In [35]:
numeric_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

print("Numerical columns:")
for column in numeric_columns:
    print(f"- {column}")

Numerical columns:
- Row ID
- Sales
- Quantity
- Discount
- Profit

In [36]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Row ID,10194.0,5097.500000,2942.898656,1.000,2549.2500,5097.50,7645.750000,10194.000
Sales,10194.0,228.225854,619.906839,0.444,17.2200,53.91,209.500000,22638.480
Quantity,10194.0,3.791838,2.228317,1.000,2.0000,3.00,5.000000,14.000
Discount,10194.0,0.155385,0.206249,0.000,0.0000,0.20,0.200000,0.800
Profit,10194.0,28.673417,232.465115,-6599.978,1.7608,8.69,29.297925,8399.976

## 13. Numerical Data Quality Checks

The following checks identify values that may require investigation.

In [37]:
quality_checks = {}

if "Sales" in df.columns:
    quality_checks["Negative Sales"] = int(
        (df["Sales"] < 0).sum()
    )

if "Quantity" in df.columns:
    quality_checks["Non-positive Quantity"] = int(
        (df["Quantity"] <= 0).sum()
    )

if "Discount" in df.columns:
    quality_checks["Discount < 0"] = int(
        (df["Discount"] < 0).sum()
    )
    
    quality_checks["Discount > 1"] = int(
        (df["Discount"] > 1).sum()
    )

if "Profit" in df.columns:
    quality_checks["Negative Profit"] = int(
        (df["Profit"] < 0).sum()
    )

numerical_quality_summary = pd.DataFrame(
    list(quality_checks.items()),
    columns=["Check", "Number of Rows"]
)

numerical_quality_summary

                   Check  Number of Rows
0         Negative Sales               0
1  Non-positive Quantity               0
2           Discount < 0               0
3           Discount > 1               0
4        Negative Profit            1901

`Row ID`: is unique for every row and is a good candidate for the unique identifier of a transaction line.

`Sales`: The mean is much higher than the median, showing that sales are strongly right-skewed: most transactions are relatively small, while a smaller number have very high sales.

`Quantity`: All transactions have a positive quantity. There are no obvious invalid quantities.

`Discount`: Discount values range from 0% to 80%. The check found no values below 0 or above 1, so there are no obviously invalid discount values.

`Profit`: Profit varies significantly. 1,901 rows have negative profit, which is about 18.65% of all transaction rows. That is not automaticlly a data-quality. It means those transactions generated losses.

***Overall numerical conclusion***

The numerical data appears structurally valid. No negative sales, zero/negative quantities, or invalid discount values were found. Profit contains legitimate negative values that should be retained because they represent loss-making transactions.

## 14. Categorical Variables

Categorical variables are inspected to identify their possible values, frequencies and potential inconsistencies.

In [38]:
categorical_columns = df.select_dtypes(
    include=["object", "string"]
).columns.tolist()

print("Categorical/Text columns:")

for column in categorical_columns:
    print(f"- {column}")

Categorical/Text columns:
- Order ID
- Order Date
- Ship Date
- Ship Mode
- Customer ID
- Customer Name
- Segment
- Country/Region
- City
- State/Province
- Postal Code
- Region
- Product ID
- Category
- Sub-Category
- Product Name

In [39]:
for column in categorical_columns:
    
    print("\n" + "=" * 70)
    print(column)
    print("=" * 70)
    
    print(
        df[column]
        .value_counts(dropna=False)
        .head(15)
    )

======================================================================
Order ID
======================================================================
Order ID
US-2026-100111    14
US-2026-157987    12
US-2025-108504    11
US-2025-165330    11
US-2024-131338    10
US-2025-105732    10
US-2024-126977    10
US-2023-106439     9
US-2024-158421     9
US-2026-140949     9
US-2026-117457     9
US-2025-145177     9
US-2024-104346     9
US-2024-164882     9
US-2024-132626     9
Name: count, dtype: int64

======================================================================
Order Date
======================================================================
Order Date
9/5/2025      38
12/2/2026     37
9/2/2026      36
11/10/2025    35
12/9/2026     35
12/1/2026     34
12/8/2026     30
11/12/2026    30
9/9/2026      29
9/4/2026      28
12/11/2025    28
11/8/2024     27
9/24/2026     27
12/22/2026    27
9/8/2023      27
Name: count, dtype: int64

======================================================================
Ship Date
======================================================================
Ship Date
12/16/2024    38
12/6/2026     35
9/26/2026     34
11/21/2026    32
9/15/2026     30
9/6/2026      30
12/12/2026    30
9/13/2023     28
11/18/2026    27
9/8/2026      27
9/7/2025      26
9/26/2024     26
11/16/2026    25
11/17/2024    25
10/1/2025     24
Name: count, dtype: int64

======================================================================
Ship Mode
======================================================================
Ship Mode
Standard Class    6120
Second Class      1979
First Class       1548
Same Day           547
Name: count, dtype: int64

======================================================================
Customer ID
======================================================================
Customer ID
WB-21850    41
BF-11170    37
GG-14650    36
JW-15220    34
JL-15835    34
PP-18955    34
MA-17560    34
XP-21865    34
EH-13765    32
CK-12205    32
SV-20365    32
JD-15895    32
AP-10915    31
ZC-21910    31
EP-13915    31
Name: count, dtype: int64

======================================================================
Customer Name
======================================================================
Customer Name
William Brown          41
Ben Ferrer             37
Greg Guthrie           36
Jane Waco              34
John Lee               34
Paul Prost             34
Matt Abelman           34
Xylona Preis           34
Edward Hooks           32
Chloris Kastensmidt    32
Seth Vernon            32
Jonathan Doherty       32
Arthur Prichep         31
Zuschuss Carroll       31
Emily Phan             31
Name: count, dtype: int64

======================================================================
Segment
======================================================================
Segment
Consumer       5281
Corporate      3090
Home Office    1823
Name: count, dtype: int64

======================================================================
Country/Region
======================================================================
Country/Region
United States    9994
Canada            200
Name: count, dtype: int64

======================================================================
City
======================================================================
City
New York City    915
Los Angeles      747
Philadelphia     537
San Francisco    510
Seattle          428
Houston          377
Chicago          314
Columbus         222
San Diego        170
Springfield      163
Dallas           157
Jacksonville     125
Detroit          115
Newark            95
Richmond          90
Name: count, dtype: int64

======================================================================
State/Province
======================================================================
State/Province
California        2001
New York          1128
Texas              985
Pennsylvania       587
Washington         506
Illinois           492
Ohio               469
Florida            383
Michigan           255
North Carolina     249
Virginia           224
Arizona            224
Georgia            184
Tennessee          183
Colorado           182
Name: count, dtype: int64

======================================================================
Postal Code
======================================================================
Postal Code
10035    263
10024    230
10009    229
94122    203
10011    193
94110    166
98105    165
19134    160
90049    151
98103    151
19140    150
94109    141
90045    140
90036    122
43229    120
Name: count, dtype: int64

======================================================================
Region
======================================================================
Region
West       3253
East       2986
Central    2335
South      1620
Name: count, dtype: int64

======================================================================
Product ID
======================================================================
Product ID
FUR-FU-10004270    20
OFF-PA-10001970    19
TEC-AC-10003832    18
FUR-CH-10002647    15
TEC-AC-10002049    15
FUR-CH-10004287    15
FUR-CH-10001146    15
TEC-AC-10003628    15
OFF-BI-10002026    14
FUR-CH-10002880    14
FUR-FU-10004973    14
OFF-PA-10002377    14
OFF-BI-10001718    14
OFF-BI-10001524    14
FUR-CH-10003774    14
Name: count, dtype: int64

======================================================================
Category
======================================================================
Category
Office Supplies    6128
Furniture          2201
Technology         1865
Name: count, dtype: int64

======================================================================
Sub-Category
======================================================================
Sub-Category
Binders        1548
Paper          1384
Furnishings    1009
Phones          903
Storage         856
Art             821
Accessories     775
Chairs          634
Appliances      474
Labels          368
Tables          326
Envelopes       256
Bookcases       232
Fasteners       229
Supplies        192
Name: count, dtype: int64

======================================================================
Product Name
======================================================================
Product Name
Staples                                                      50
Staple envelope                                              48
Easy-staple paper                                            46
KI Adjustable-Height Table                                   20
Avery Non-Stick Binders                                      20
Staples in misc. colors                                      19
Staple remover                                               18
Storex Dura Pro Binders                                      17
Staple-based wall hangings                                   16
Logitech 910-002974 M325 Wireless Mouse for Web Scrolling    15
Situations Contoured Folding Chairs, 4/Set                   15
SAFCO Arco Folding Chair                                     15
Global High-Back Leather Tilter, Burgundy                    14
Eldon Wave Desk Accessories                                  14
GBC DocuBind P50 Personal Binding Machine                    14
Name: count, dtype: int64

The dataset has:

- 4 shipping modes
- 3 customer segments
- 2 countries
- 4 regions
- 3 categories
- 17 sub-categories

The frequency distributions show that the data is not evenly distributed.
- *Ship Mode*: Standard Class = 6,120 / 10,194 ≈ 60%
- *Country*: United States = 9,994 and Canada = 200

For product categories:
- Office Supplies = 6,128
- Furniture       = 2,201
- Technology      = 1,865

***Conclusion***

The categorical fields contain a manageable number of categories and are suitable for dimensional analysis and Power BI filtering. No obvious unexpected category values are visible from the results provided.

## 15. Date Analysis

In [41]:
possible_date_columns = [
    column
    for column in df.columns
    if "date" in column.lower()
]

print("Possible date columns:")

for column in possible_date_columns:
    print(f"- {column}")

Possible date columns:
- Order Date
- Ship Date

In [42]:
date_analysis = {}

for column in possible_date_columns:
    
    temp_dates = pd.to_datetime(
        df[column],
        errors="coerce"
    )
    
    date_analysis[column] = {
        "Original Data Type": str(df[column].dtype),
        "Invalid / Unreadable Dates": int(temp_dates.isna().sum()),
        "Minimum Date": temp_dates.min(),
        "Maximum Date": temp_dates.max()
    }

date_analysis_df = pd.DataFrame(date_analysis).T

date_analysis_df

,Original Data Type,Invalid / Unreadable Dates,Minimum Date,Maximum Date
Order Date,object,0,2023-01-03 00:00:00,2026-12-30 00:00:00
Ship Date,object,0,2023-01-07 00:00:00,2027-01-05 00:00:00

### 15. 1. Order Date vs Ship Date Validation

A shipment should not normally occur before the corresponding order.

This check identifies such records without modifying the dataset.

In [43]:
order_dates = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

ship_dates = pd.to_datetime(
    df["Ship Date"],
    errors="coerce"
)

invalid_shipping_dates = ship_dates < order_dates

print(
    "Rows where Ship Date is before Order Date:",
    int(invalid_shipping_dates.sum())
)

Rows where Ship Date is before Order Date: 0

In [44]:
invalid_shipping_records = df[
    invalid_shipping_dates
]

invalid_shipping_records.head(20)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State/Province, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

### 15.02. Shipping Duration

In [45]:
shipping_days = (
    ship_dates - order_dates
).dt.days

shipping_days.describe()

count    10194.000000
mean         3.961350
std          1.742829
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max         11.000000
dtype: float64

In [46]:
shipping_days = (
    ship_dates - order_dates
).dt.days

shipping_days.describe()

count    10194.000000
mean         3.961350
std          1.742829
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max         11.000000
dtype: float64

In [47]:
print(
    "Orders with negative shipping duration:",
    int((shipping_days < 0).sum())
)

print(
    "Average shipping duration:",
    shipping_days.mean()
)

print(
    "Maximum shipping duration:",
    shipping_days.max()
)

Orders with negative shipping duration: 0
Average shipping duration: 3.9613498136158523
Maximum shipping duration: 11

***Conclusion***

The date fields are readable and logically consistent. However, `Order Date` and `Ship Date` are currently stored as text and will need to be converted to proper date types during SQL transformation.

Shipping dates are logically consistent, with shipping taking between 0 and 11 days and an average of approximately 4 days.

## 16. Geographic Fields

In [48]:
geographic_columns = [
    column
    for column in [
        "Country/Region",
        "State/Province",
        "City",
        "Postal Code",
        "Region"
    ]
    if column in df.columns
]

print("Available geographic columns:")

for column in geographic_columns:
    print(f"- {column}")

Available geographic columns:
- Country/Region
- State/Province
- City
- Postal Code
- Region

In [49]:
for column in geographic_columns:
    
    print("\n" + "=" * 70)
    print(column)
    print("=" * 70)
    
    print("Unique values:", df[column].nunique(dropna=True))
    
    print("\nTop values:")
    print(
        df[column]
        .value_counts(dropna=False)
        .head(10)
    )

======================================================================
Country/Region
======================================================================
Unique values: 2

Top values:
Country/Region
United States    9994
Canada            200
Name: count, dtype: int64

======================================================================
State/Province
======================================================================
Unique values: 59

Top values:
State/Province
California        2001
New York          1128
Texas              985
Pennsylvania       587
Washington         506
Illinois           492
Ohio               469
Florida            383
Michigan           255
North Carolina     249
Name: count, dtype: int64

======================================================================
City
======================================================================
Unique values: 542

Top values:
City
New York City    915
Los Angeles      747
Philadelphia     537
San Francisco    510
Seattle          428
Houston          377
Chicago          314
Columbus         222
San Diego        170
Springfield      163
Name: count, dtype: int64

======================================================================
Postal Code
======================================================================
Unique values: 654

Top values:
Postal Code
10035    263
10024    230
10009    229
94122    203
10011    193
94110    166
98105    165
19134    160
90049    151
98103    151
Name: count, dtype: int64

======================================================================
Region
======================================================================
Unique values: 4

Top values:
Region
West       3253
East       2986
Central    2335
South      1620
Name: count, dtype: int64

***Conclusion***

The dataset supports geographic analysis at country, region, state/province, city and postal-code levels. This can directly support regional sales and profit analysis in Power BI.

## 17. Basic Business-Level Summary

These figures will be used as baseline validation values.

The same metrics will later be calculated in SQL Server and Power BI.

If the transformations are correct, the corresponding totals should remain consistent.

In [50]:
business_summary = {
    "Total Sales": df["Sales"].sum(),
    "Total Profit": df["Profit"].sum(),
    "Total Quantity": df["Quantity"].sum(),
    "Unique Orders": df["Order ID"].nunique(),
    "Unique Customers": df["Customer ID"].nunique(),
    "Unique Products": df["Product ID"].nunique()
}

business_summary_df = pd.DataFrame(
    list(business_summary.items()),
    columns=["Metric", "Value"]
)

business_summary_df

             Metric         Value
0       Total Sales  2.326534e+06
1      Total Profit  2.922968e+05
2    Total Quantity  3.865400e+04
3     Unique Orders  5.111000e+03
4  Unique Customers  8.040000e+02
5   Unique Products  1.862000e+03

## 18. Initial Data Quality Summary

This summary brings together the main structural and quality results identified during profiling.

In [51]:
initial_quality_summary = {
    "Rows": len(df),
    "Columns": len(df.columns),
    "Exact Duplicate Rows": int(df.duplicated().sum()),
    "Columns With Missing Values": int(
        (df.isna().sum() > 0).sum()
    ),
    "Total Missing Cells": int(
        df.isna().sum().sum()
    ),
    "Unique Orders": int(
        df["Order ID"].nunique()
    ),
    "Unique Customers": int(
        df["Customer ID"].nunique()
    ),
    "Unique Products": int(
        df["Product ID"].nunique()
    )
}

initial_quality_summary_df = pd.DataFrame(
    list(initial_quality_summary.items()),
    columns=["Metric", "Value"]
)

initial_quality_summary_df

                        Metric  Value
0                         Rows  10194
1                      Columns     21
2         Exact Duplicate Rows      0
3  Columns With Missing Values      0
4          Total Missing Cells      0
5                Unique Orders   5111
6             Unique Customers    804
7              Unique Products   1862

## 19. Save Profiling Outputs

The main profiling summaries are saved as CSV files so that the results can be referenced during the SQL and validation stages.

In [52]:
output_folder = nt_folder / "profiling_outputs"
output_folder.mkdir(exist_ok=True)

# Basic profiling summaries

missing_summary.to_csv(
    output_folder / "01_missing_values_summary.csv",
    index=False
)

unique_summary.to_csv(
    output_folder / "02_unique_values_summary.csv",
    index=False
)

identifier_summary.to_csv(
    output_folder / "03_identifier_summary.csv",
    index=False
)

# Transactional grain

transaction_line_distribution.to_csv(
    output_folder / "04_transaction_line_distribution.csv",
    index=False
)

largest_orders.to_csv(
    output_folder / "05_largest_orders.csv",
    index=False
)


# Customer relationship analysis

customer_id_consistency.to_csv(
    output_folder / "06_customer_id_consistency.csv"
)

inconsistent_customers.to_csv(
    output_folder / "07_inconsistent_customers.csv"
)

multiple_ids_same_name.to_csv(
    output_folder / "08_customer_names_multiple_ids.csv"
)


# Product relationship analysis

product_id_consistency.to_csv(
    output_folder / "09_product_id_consistency.csv"
)

inconsistent_products.to_csv(
    output_folder / "10_inconsistent_products.csv"
)

multiple_ids_same_product.to_csv(
    output_folder / "11_product_names_multiple_ids.csv"
)


# Order consistency


multiple_customers_per_order.to_csv(
    output_folder / "12_orders_multiple_customers.csv"
)

multiple_order_dates.to_csv(
    output_folder / "13_orders_multiple_order_dates.csv"
)

multiple_ship_dates.to_csv(
    output_folder / "14_orders_multiple_ship_dates.csv"
)


# Numerical analysis


numerical_quality_summary.to_csv(
    output_folder / "15_numerical_quality_summary.csv",
    index=False
)


# Date analysis


date_analysis_df.to_csv(
    output_folder / "16_date_analysis.csv"
)

# Shipping duration summary
shipping_duration_summary = shipping_days.describe().to_frame(
    name="Shipping Days"
)

shipping_duration_summary.to_csv(
    output_folder / "17_shipping_duration_summary.csv"
)


# Business summary


business_summary_df.to_csv(
    output_folder / "18_business_summary.csv",
    index=False
)


# Final quality overview


initial_quality_summary = {
    "Rows": len(df),
    "Columns": len(df.columns),
    "Exact Duplicate Rows": int(df.duplicated().sum()),
    "Columns With Missing Values": int(
        (df.isna().sum() > 0).sum()
    ),
    "Total Missing Cells": int(
        df.isna().sum().sum()
    ),
    "Unique Orders": int(df["Order ID"].nunique()),
    "Unique Customers": int(df["Customer ID"].nunique()),
    "Unique Products": int(df["Product ID"].nunique()),
    "Orders With Multiple Customers": int(
        len(multiple_customers_per_order)
    ),
    "Inconsistent Product IDs": int(
        len(inconsistent_products)
    ),
    "Product Names With Multiple IDs": int(
        len(multiple_ids_same_product)
    ),
    "Negative Profit Rows": int(
        (df["Profit"] < 0).sum()
    )
}

initial_quality_summary_df = pd.DataFrame(
    list(initial_quality_summary.items()),
    columns=["Metric", "Value"]
)

initial_quality_summary_df.to_csv(
    output_folder / "19_initial_quality_summary.csv",
    index=False
)

print("All profiling outputs saved successfully.")
print(f"Output folder: {output_folder}")

All profiling outputs saved successfully.
Output folder: C:\Users\may\Documents\Syntecxhub_Sales_Performance_Dashboard\Initial Data Profiling\profiling_outputs

# Initial Data Profiling — Final Conclusions

## 1. Dataset Structure

The raw dataset contains 10,194 transaction rows and 21 columns.

It includes information about orders, customers, products, shipping, geography and financial performance.

The dataset is suitable for building a sales performance analytics solution.

---

## 2. Transactional Grain

There are 5,111 unique Order IDs across 10,194 transaction rows.

The average order contains approximately 1.99 transaction lines, and 2,518 orders (49.27%) contain more than one transaction line.

The largest observed order contains 14 transaction lines.

Row ID contains 10,194 unique values, matching the number of transaction rows. Therefore, Row ID is a strong candidate for uniquely identifying each transaction line.

The fact table must preserve the transaction-line grain rather than aggregating the raw data to one row per Order ID.

---

## 3. Missing Values

No missing values were found in any column.

No rows need to be removed or values filled because of missing data.

SQL validation will still confirm this during the staging stage.

---

## 4. Duplicate Records

No exact duplicate rows were found.

Repeated Order IDs are not considered duplicate rows because an order can contain multiple transaction lines for different products.

No duplicate-row removal is required.

---

## 5. Data Types

The following data-type changes will be required during SQL transformation:

- Order Date: convert from text to DATE.
- Ship Date: convert from text to DATE.
- Postal Code: keep as text because it is an identifier and can contain letters.

The other fields will be assigned appropriate SQL data types during staging.

---

## 6. Customer Data

There are 804 unique Customer IDs and 800 unique Customer Names.

Each Customer ID consistently maps to one Customer Name and one Segment.

However, one customer name, Harry Olson, appears with five different Customer IDs.

Therefore, Customer Name must not be used as the customer key.

Customer ID will be used as the reliable customer business identifier.

No customer rows should be removed because of the repeated name.

---

## 7. Product Data

There are 1,862 unique Product IDs and 1,849 unique Product Names.

32 Product IDs are associated with two different Product Names.

Their Category and Sub-Category remain consistent, so the inconsistency is specifically in Product Name.

There are also 17 Product Names associated with multiple Product IDs.

Therefore, Product ID and Product Name cannot be treated as a perfect one-to-one relationship in the raw data.

The 32 inconsistent Product IDs must be investigated and standardized during SQL cleaning before creating the product dimension.

The affected rows should not be deleted.

Category and Sub-Category should be validated and preserved.

---

## 8. Order Consistency

The Order ID correctly groups multiple transaction lines.

Order Date is consistent within each order, with zero orders associated with multiple Order Dates.

Ship Date is also consistent within each order, with zero orders associated with multiple Ship Dates.

However, 2 orders are associated with multiple Customer IDs.

These 2 orders must be investigated during SQL data-quality validation before the final dimensional model is created.

No rows should be removed at the profiling stage.

---

## 9. Numerical Data

Row ID is unique for every transaction line.

Sales contains no negative values.

Quantity contains no zero or negative values.

Discount contains no values below 0 or above 1.

Profit contains 1,901 negative-profit rows, representing approximately 18.65% of transaction rows.

Negative Profit is not treated as a data-quality error because it represents loss-making transactions and is important for profitability analysis.

These rows must therefore be retained.

---

## 10. Categorical Data

The main categorical fields have a manageable number of values:

- 4 Ship Modes
- 3 Customer Segments
- 2 Countries
- 4 Regions
- 3 Categories
- 17 Sub-Categories

The frequency distributions do not show obvious unexpected category values.

These fields are suitable for filtering, grouping and dimensional analysis in Power BI.

---

## 11. Date Data

Order Date ranges from 2023-01-03 to 2026-12-30.

Ship Date ranges from 2023-01-07 to 2027-01-05.

All dates were successfully interpreted during profiling.

No shipment occurs before its corresponding order.

Shipping duration ranges from 0 to 11 days, with an average of approximately 3.96 days.

A derived shipping-duration measure can later be used for shipping-performance analysis.

The future-dated records should not be removed simply because they occur after the current date; the dataset's own date range should be preserved unless a business requirement later establishes a valid reporting cutoff.

---

## 12. Geographic Data

The dataset contains:

- 2 countries
- 4 regions
- 59 states/provinces
- 542 cities
- 654 postal codes

This supports geographic analysis at several levels and provides enough detail for regional sales and profitability analysis.

Postal Code should remain a text identifier.

---

## 13. Changes Required During the SQL Stage

Based on the profiling results, the following actions are required:

### Data type transformations

- Convert Order Date to DATE.
- Convert Ship Date to DATE.
- Store Postal Code as VARCHAR/NVARCHAR.
- Assign appropriate SQL data types to the remaining columns.

### Data-quality investigations

- Investigate the 2 orders associated with multiple Customer IDs.
- Investigate the 32 Product IDs associated with multiple Product Names.
- Determine how Product Name inconsistencies should be standardized.
- Validate Product ID → Category and Product ID → Sub-Category relationships.

### Data modeling

- Preserve one row per transaction/order line.
- Use Row ID as the transaction-line identifier.
- Use Customer ID as the customer business identifier.
- Use Product ID as the product business identifier.
- Create a Date Dimension.
- Create the appropriate fact and dimension tables after the relationship checks are completed.

### Values that should NOT be removed

- Negative-profit transactions.
- Repeated Order IDs representing multiple transaction lines.
- Customers sharing the same name.
- Product rows affected by Product ID/Product Name inconsistencies, until the issue has been investigated.

### Values that currently require no treatment

- Missing values: none found.
- Exact duplicate rows: none found.
- Negative Sales: none found.
- Non-positive Quantity: none found.
- Invalid Discount values: none found.
- Ship Date before Order Date: none found.

---

## 14. Final Conclusion

The dataset does not require general row deletion or missing-value treatment.

The main work in the next stage is therefore to perform controlled SQL transformations and investigate the identified relationship inconsistencies.